### ISSUE TITLE
Expand Promises material

### ISSUE THREAD

**Issue by gvwilson** [rangle/js-training#2]
Expand material on Promises and add material on Observables.

**Comment by sonukapoor** [comment]
- [ ] Start with callbacks before going into promises. Explain what the 'Pyramid of Doom' is when working with callbacks.
- [ ] Keep first example simple - maybe just two lines using $http.
- [ ] Show how we can chain promises using `then`
- [ ] Show why `.then()...then()...` is bad
- [ ] Show how to chain properly
- [ ] Explain Error Handling
- [ ] Explain Promise Statuses
- [ ] Explain How to caching Promise results
